# src/main/resources/application.yml
server:
  port: 8084

spring:
  application:
    name: dispatch-service
  datasource:
    url: jdbc:mysql://localhost:3306/dispatch?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: MinhLuan.1004
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  jwt:
    secret: "MinhLuanSuperSecretKey_1234567890"
  gateway:
    base-url: "http://localhost:8085"
